[features]
seeds = false
skip-lint = false
[programs.localnet]
automated_vault = "6tBxv2wSiyGgrjqQ1Aw92Ant4CD8Gt9RBvYvWtEAGSE1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/madhan/.config/solana/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
